from dialogs.base_dialog import BaseDialog
from dialogs.category_dialog import CategoryDialog
from dialogs.account_dialog import AccountDialog
from dialogs.transaction_dialog import TransactionDialog
from dialogs.confirm_dialog import ConfirmDialog